### ISSUE TITLE
Server is not robust against slightly malformed cookies header

### ISSUE THREAD

**Issue by talljosh** [nullism/pycnic#31]
I was using `curl` to try the `full-auth.py` [example](https://github.com/nullism/pycnic/blob/master/examples/full-auth.py).

I ran `/login` successfully, which gave this response:
```
HTTP/1.0 200 OK
Date: Tue, 16 Feb 2021 06:49:09 GMT
Server: WSGIServer/0.2 CPython/3.8.5
Content-Type: application/json
Set-Cookie: session_id=c14138a45dce834f08e476522a00d605c55ace6a; path=/; 

{"message": "Logged in", "session_id": "c14138a45dce834f08e476522a00d605c55ace6a"}
```

I then tried to run `/home` by copying and pasting the entire cookie string to curl:
```
curl -i -X GET http://localhost:8080/home --cookie "session_id=c14138a45dce834f08e476522a00d605c55ace6a; path=/;"
```
The result was an error:
```
HTTP/1.0 500 Internal Server Error
Date: Tue, 16 Feb 2021 06:49:46 GMT
Server: WSGIServer/0.2 CPython/3.8.5
Content-Type: application/json

{"error": "Internal server error encountered."}
```

It turns out that the error is because of the trailing semicolon in the cookie string. (I shouldn't have pasted the `path=` part either, but the trailing semicolon is what breaks it.)
```
Traceback (most recent call last):
  File "/home/josh/.local/lib/python3.8/site-packages/pycnic/core.py", line 235, in __iter__
    resp = self.delegate()
  File "/home/josh/.local/lib/python3.8/site-packages/pycnic/core.py", line 308, in delegate
    output = func(*args)
  File "full-auth.py", line 33, in wrapped
    if not get_user(args[0].request):
  File "full-auth.py", line 14, in get_user
    sess_id = request.cookies.get("session_id")
  File "/home/josh/.local/lib/python3.8/site-packages/pycnic/core.py", line 124, in cookies
    cname, cvalue = cookie_line.strip().split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

A malformed cookie header shouldn't result in a server error. Pycnic should either silently ignore the trailing comma, or it should return `400 Bad Request`.

**Comment by nullism** [comment]
Thanks for letting me know, I'll push a fixed version to pypy after work today.

**Comment by nullism** [comment]
in 0.1.6

**Comment by talljosh** [comment]
Thanks for the very quick response!
