### ISSUE TITLE
QUERY_STRING is assumed

### ISSUE THREAD

**Issue by aronatkins** [nullism/pycnic#35]
According to https://github.com/jonashaag/bjoern/issues/118, `QUERY_STRING` cannot be assumed as part of the incoming environment.

`Request.args` and `Request.json_args` should assume `QUERY_STRING=""` when it is not present in the environment.

https://github.com/nullism/pycnic/blob/1e60f41d01a4940c5ade0e9d7981d5fa71af67bd/pycnic/core.py#L77-L96

Example application:

```python
from pycnic.core import WSGI, Handler

class Hello(Handler):
    def get(self):
        name = self.request.args.get("name", "Pycnic")
        return {"msg": "Hello, %s!" % (name)}

class app(WSGI):
    routes = [("/hello", Hello())]

if __name__ == "__main__":
    import bjoern
    bjoern.run(app, "127.0.0.1", 8000)
```

When run, requests to `http://localhost:8000` err:

```
'QUERY_STRING'
Traceback (most recent call last):
  File "/XXXX/lib/python3.8/site-packages/pycnic/core.py", line 237, in __iter__
    resp = self.delegate()
  File "/XXXX/lib/python3.8/site-packages/pycnic/core.py", line 310, in delegate
    output = func(*args)
  File "app.py", line 6, in get
    name = self.request.args.get("name", "Pycnic")
  File "/XXXX/lib/python3.8/site-packages/pycnic/core.py", line 81, in args
    qs = self.environ["QUERY_STRING"]
KeyError: 'QUERY_STRING'
```

**Comment by aronatkins** [comment]
Requests with a query are just fine:

```bash
curl http://localhost:8000/hello\?name\=bob
# => {"msg": "Hello, bob!"}
```

**Comment by aronatkins** [comment]
Related: https://peps.python.org/pep-0333/#environ-variables

> QUERY_STRING
> The portion of the request URL that follows the "?", if any. May be empty or absent.

**Comment by aronatkins** [comment]
Workaround, in case others hit this is to add a middleware to ensure that `QUERY_STRING` is set.

```python
from pycnic.core import WSGI, Handler

class EnvironMiddleware(object):
    def __init__(self, app):
        self.app = app

    def __call__(self, environ, start_response):
        if environ.get("QUERY_STRING") is None:
            environ["QUERY_STRING"] = ""
        return self.app(environ, start_response)

class Hello(Handler):
    def get(self):
        name = self.request.args.get("name", "Pycnic")
        return {"msg": "Hello, %s!" % (name)}

class app(WSGI):
    routes = [("/hello", Hello())]

if __name__ == "__main__":
    import bjoern
    wrapped = EnvironMiddleware(app)
    bjoern.run(wrapped, "127.0.0.1", 8000)
```
